(defpackage #:a2a-protocol
  (:use #:cl)
  (:nicknames #:stack-a2a)
  (:export
   #:+a2a-protocol-version+
   #:*supported-protocol-versions*
   #:+a2a-error-task-not-found+
   #:+a2a-error-task-not-cancelable+
   #:+a2a-error-push-not-supported+
   #:+a2a-error-unsupported-operation+
   #:+a2a-error-content-type-not-supported+
   #:+a2a-error-invalid-agent-response+
   #:+a2a-error-extended-card-not-configured+
   #:+a2a-error-extension-support-required+
   #:+a2a-error-version-not-supported+
   #:a2a-error
   #:a2a-error-message
   #:a2a-error-code
   #:a2a-error-data
   #:a2a-backend
   #:a2a-agent
   #:a2a-agent-name
   #:a2a-agent-card
   #:a2a-agent-extended-card
   #:a2a-agent-handler
   #:a2a-agent-streaming-p
   #:make-a2a-agent
   #:agent-card
   #:agent-card-name
   #:agent-card-description
   #:agent-card-version
   #:agent-card-supported-interfaces
   #:agent-card-capabilities
   #:agent-card-default-input-modes
   #:agent-card-default-output-modes
   #:agent-card-skills
   #:agent-card-url
   #:make-agent-card
   #:agent-interface
   #:agent-interface-url
   #:agent-interface-protocol-binding
   #:agent-interface-protocol-version
   #:agent-interface-tenant
   #:make-agent-interface
   #:agent-skill
   #:agent-skill-id
   #:agent-skill-name
   #:agent-skill-description
   #:agent-skill-tags
   #:make-agent-skill
   #:a2a-task
   #:a2a-task-id
   #:a2a-task-context-id
   #:a2a-task-status
   #:a2a-task-artifacts
   #:a2a-task-history
   #:a2a-task-metadata
   #:make-a2a-task
   #:a2a-task-state
   #:task-status
   #:task-status-state
   #:task-status-message
   #:task-status-timestamp
   #:make-task-status
   #:a2a-message
   #:a2a-message-id
   #:a2a-message-context-id
   #:a2a-message-task-id
   #:a2a-message-role
   #:a2a-message-parts
   #:a2a-message-metadata
   #:make-a2a-message
   #:a2a-part
   #:a2a-part-text
   #:a2a-part-raw
   #:a2a-part-url
   #:a2a-part-data
   #:a2a-part-filename
   #:a2a-part-media-type
   #:a2a-part-metadata
   #:make-text-part
   #:make-data-part
   #:make-file-part
   #:message-text
   #:a2a-artifact
   #:a2a-artifact-id
   #:a2a-artifact-name
   #:a2a-artifact-description
   #:a2a-artifact-parts
   #:make-a2a-artifact
   #:a2a-stream-result
   #:a2a-stream-events
   #:make-a2a-stream-result
   #:*a2a-backend*
   #:fetch-agent-card
   #:serve-agent-card
   #:send-message
   #:stream-message
   #:get-task
   #:list-tasks
   #:cancel-task
   #:resubscribe-task
   #:dispatch-a2a-method
   #:serve-a2a
   #:json-object
   #:param
   #:encode-json
   #:decode-json
   #:encode-agent-card
   #:decode-agent-card
   #:encode-task
   #:decode-task
   #:encode-message
   #:decode-message
   #:encode-send-result
   #:decode-send-result
   #:encode-stream-event
   #:task-state-to-wire
   #:task-state-from-wire
   #:role-to-wire
   #:role-from-wire
   #:terminal-state-p
   #:make-id)
  (:documentation
   "A2A 1.0 CLOS protocol. JSON-RPC methods are PascalCase (SendMessage, …);
    slash aliases (message/send, …) are accepted on dispatch."))

(in-package #:a2a-protocol)
